@URL_API = http://user:user@localhost:8080/api

POST {{URL_API}}/user/new
    Content-Type: application/json

    {
        "username": "user",
        "password": "user"
    }

#########
# TENANT
#########

GET {{URL_API}}/tenant/list?sort=id,asc
    Content-Type: application/json

###
POST {{URL_API}}/tenant
    Content-Type: application/json

    {
        "name": "João Teste 2",
        "contacts": [
            {
                "type": "Email",
                "contact": "teste@gmail.com"
            }
        ],
        "document": "123742d2332434",
        "cpfCnpj": "22337432d333423",
        "dateOfBirth": "1990-10-10",
        "address": "Teste de endereço",
        "maritalStatus": "Casado(a)"
    }

###
PUT {{URL_API}}/tenant/1
    Content-Type: application/json

    {
        "id": 1,
        "name": "Rodrigo Caliman",
        "contacts": [
            {
                "type": "Email",
                "contact": "rcaliman@teste.com"
            }
        ],
        "document": "1442223dda",
        "cpfCnpj": "223233424dd23aa",
        "dateOfBirth": "1990-10-10",
        "address": "Teste de endereço",
        "maritalStatus": "Casado(a)",
        "type": "Locatário(a)"
    }

###
GET {{URL_API}}/tenant/cpfCnpj/22337432d333423
    Content-Type: application/json

###
GET {{URL_API}}/tenant/id/1
    Content-Type: application/json

###
DELETE {{URL_API}}/tenant/1

############
# LANDLORD
############
POST {{URL_API}}/landlord
    Content-Type: application/json

    {
        "name": "João Landlord",
        "contacts": [
            {
                "type": "Email",
                "contact": "teste@gmail.com"
            }
        ],
        "document": "132372d2d434",
        "cpfCnpj": "2233d344d3423",
        "dateOfBirth": "1990-10-10",
        "address": "Teste de endereço",
        "maritalStatus": "Casado(a)"
    }

###
GET {{URL_API}}/landlord/cpfCnpj/2233344d3423
    Content-Type: application/json

###
GET {{URL_API}}/landlord/1
    Content-Type: application/json

###
GET {{URL_API}}/landlord/list
    Content-Type: application/json

###
DELETE {{URL_API}}/landlord/1

###########
# PROPERTY
###########

POST {{URL_API}}/property
    Content-Type: application/json

    {
        "type":"Loja",
        "address":"Travessa Jose toledo",
        "number": "100",
        "tenantId": 1,
        "value": "1000.0",
        "complement":"teste de complemento",
        "observation": "teste de observacao",
        "paymentDay":"20"
    }


###
GET {{URL_API}}/property/1
    Content-Type: application/json

###
PUT {{URL_API}}/property/1
    Content-Type: application/json

    {
        "type":"Loja",
        "address":"Travessa Jose toledo",
        "number": "200",
        "tenantId": 1,
        "value": "1100.0",
        "complement":"teste de complemento",
        "observation": "teste de observacao",
        "paymentDay":"21"
    }

###
GET {{URL_API}}/property/list
    Content-Type: application/json

###
DELETE {{URL_API}}/property/1

###
POST {{URL_API}}/receipt
    Content-Type: application/json

    {
        "propertyIds": [1],
        "landlordId": 1,
        "locale": "Colatina-ES",
        "day": "10",
        "month": "Agosto",
        "year": "2025"
    }

#########
# ENERGY
#########

GET {{URL_API}}/energy/lasts

###
POST {{URL_API}}/energy
    Content-Type: application/json

    {
        "counter1": 13842,
        "counter2": 20307,
        "counter3": 15046,
        "kwhValue": 0.926777,
        "billAmount": 297.64,
        "date": "2025-09-08"
    }

###
# 164	62.21	110.06	125.37	297.64	13842	20307	15046	2025-09-08	0.926777
###
PUT {{URL_API}}/energy/174
    Content-Type: application/json

    {
        "id": 174,
        "counter1": 13842,
        "counter2": 20307,
        "counter3": 15046,
        "amount1": 62.20771704180064,
        "amount2": 110.05980707395499,
        "amount3": 125.37247588424437,
        "kwhValue": 0.926777,
        "billAmount": 297.64,
        "date": "2025-09-08",
        "last": false
    }